In [11]:
import numpy as np
np.random.seed(1)
A = np.random.randn(4, 3)
print(A)


def powerIter(T):
    n = T.shape[1]
    v = np.random.randn(n)
    v = v / np.linalg.norm(v)
    for k in range(10):
        w = np.dot(T, v)
        v = w / np.linalg.norm(w)
    sigma = np.dot(v.transpose(), np.dot(T, v))
    sigma = np.sqrt(sigma)
    return v, sigma

def svdPowerIter(A):
    n = A.shape[1]
    B = np.copy(A)
    for j in range(1, n+1):
        T = np.matmul(A.transpose(), A)
        v, sigma = powerIter(T)
        u =  np.dot(A, v) / sigma
        A = A -  sigma * np.outer(u, v)
        print("j {} v {} sigma {} u {}".format(j, v, sigma, u))
        

def svdPowerIter2(A):
    n = A.shape[1]
    B = np.copy(A)
    P = np.matmul(A.transpose(), A)
    vList = [None] * n
    sigmaList = [None] * n
    uList = [None] * n
    for j in range(0, n):
        #T = P 
        lSum = np.zeros((n, n))
        for i in range(0, j):
            lSum += np.outer(vList[i], vList[i])
        print(lSum)
        lSum = np.eye(n) - lSum
        T = lSum @ P @ lSum 
        print("T {}".format(T))
        vList[j], sigmaList[j] = powerIter(T)
        uList[j] =  np.dot(A, vList[j]) / sigmaList[j]
        print("j {} v {} sigma {} u {}".format(j, vList[j], sigmaList[j], uList[j]))

#T = np.matmul(A.transpose(), A)
#print(T)
#v, sigma = powerIter(T)
#u =  np.dot(A, v) / sigma
#print("v {} sigma {} u {}".format(v, sigma, u))

U, Sigma, V = np.linalg.svd(A)
print("U {}".format(U))
print("V {}".format(V))
print("Sigma{}".format(Sigma))

#svdPowerIter(A)
svdPowerIter2(A)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]]
U [[-0.17330388  0.72332071  0.26166214  0.61506572]
 [ 0.6804161   0.15967861  0.65954611 -0.27665068]
 [-0.3691172   0.56196726 -0.06456915 -0.73741177]
 [ 0.60889423  0.36810689 -0.7016856   0.0371813 ]]
V [[-0.46899222  0.48421055 -0.73863823]
 [ 0.81556069 -0.08355492 -0.57260749]
 [-0.33897945 -0.87095276 -0.35571649]]
Sigma[3.85390339 2.32027447 0.64996275]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
T [[ 6.8963132  -3.61502809  2.6819467 ]
 [-3.61502809  3.84037184 -4.92365953]
 [ 2.6819467  -4.92365953  9.92201146]]
j 0 v [ 0.46895999 -0.48420725  0.73866086] sigma 3.8539033867443577 u [ 0.17328667 -0.6804199   0.36910383 -0.60890299]
[[ 0.21992348 -0.22707383  0.34640239]
 [-0.22707383  0.23445666 -0.35766494]
 [ 0.34640239 -0.35766494  0.54561986]]
T [[ 3.62959792 -0.24223543 -2.46314443]
 [-0.24223543  0.35805725  0.38850393]
