In [31]:
import numpy as np
np.random.seed(1)
A = np.random.randn(4, 2)
print(A)


def powerIter(T):
    n = T.shape[1]
    v = np.random.randn(n)
    v = v / np.linalg.norm(v)
    for k in range(10):
        w = np.dot(T, v)
        v = w / np.linalg.norm(w)
    sigma = np.dot(v.transpose(), np.dot(T, v))
    sigma = np.sqrt(sigma)
    return v, sigma

def svdPowerIter(A):
    n = A.shape[1]
    B = np.copy(A)
    for j in range(1, n+1):
        T = np.matmul(A.transpose(), A)
        v, sigma = powerIter(T)
        u =  np.dot(A, v) / sigma
        A = A -  sigma * np.outer(u, v)
        print("j {} v {} sigma {} u {}".format(j, v, sigma, u))
        

#T = np.matmul(A.transpose(), A)
#print(T)
#v, sigma = powerIter(T)
#u =  np.dot(A, v) / sigma
#print("v {} sigma {} u {}".format(v, sigma, u))

U, Sigma, V = np.linalg.svd(A)
print("U {}".format(U))
print("V {}".format(V))
print("Sigma{}".format(Sigma))

svdPowerIter(A)

[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069 ]]
U [[-0.47018853  0.43417392 -0.37323927 -0.67164589]
 [-0.1328186  -0.61343304 -0.76862834  0.12357022]
 [-0.6942869  -0.50223671  0.50190544 -0.11753687]
 [-0.52843889  0.42772795 -0.13414118  0.72097662]]
V [[-0.67384939  0.73886873]
 [ 0.73886873  0.67384939]]
Sigma[3.2892589  1.81481721]
j 1 v [ 0.67385025 -0.73886795] sigma 3.2892588995030305 u [0.47018881 0.1328182  0.69428658 0.52843916]
j 2 v [-0.73886795 -0.67385025] sigma 1.8148172091994406 u [-0.43417293  0.61343332  0.50223816 -0.42772684]
