In [6]:
import numpy as np
np.random.seed(1)
M = 4
N = 3 
A = np.random.randn(M, N)
print("A {}".format(A))


def qrGramSchmidt(A):
    n = A.shape[1]
    m = A.shape[0]
    R = np.zeros((n, n))
    Q = np.zeros((m, n))

    for j in range(0, n):
        u = A[:, j]
        for k in range(0, j):
            u = u - np.dot(Q[:, k], A[:, j]) * Q[:, k]
        Q[:, j] = u  / np.linalg.norm(u)
        for i in range(0, j+1):
            R[i, j] = np.dot(A[:, j], Q[:, i])

    return Q, R


#T = np.matmul(A.transpose(), A)
#print(T)
#v, sigma = powerIter(T)
#u =  np.dot(A, v) / sigma
#print("v {} sigma {} u {}".format(v, sigma, u))

Q, R = np.linalg.qr(A)
print("Q {}".format(Q))
print("R {}".format(R))

#svdPowerIter(A)
Q, R = qrGramSchmidt(A)
print("Q {}".format(Q))
print("R {}".format(R))

A [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]]
Q [[-0.61854298 -0.17187122  0.45777617]
 [ 0.40858134 -0.21721173  0.84222607]
 [-0.66441602 -0.10999556  0.05173219]
 [ 0.09495905 -0.95455766 -0.28003573]]
R [[-2.62608324  1.37658549 -1.02127254]
 [ 0.         -1.39477031  2.52212894]
 [ 0.          0.         -1.58678274]]
Q [[ 0.61854298  0.17187122 -0.45777617]
 [-0.40858134  0.21721173 -0.84222607]
 [ 0.66441602  0.10999556 -0.05173219]
 [-0.09495905  0.95455766  0.28003573]]
R [[ 2.62608324 -1.37658549  1.02127254]
 [ 0.          1.39477031 -2.52212894]
 [ 0.          0.          1.58678274]]
