In [2]:
import numpy as np
np.random.seed(1)
A = np.random.randn(4, 3)
print(A)


def powerIter(T):
    n = T.shape[1]
    v = np.random.randn(n)
    v = v / np.linalg.norm(v)
    for k in range(10):
        w = np.dot(T, v)
        v = w / np.linalg.norm(w)
    sigma = np.dot(v.transpose(), np.dot(T, v))
    sigma = np.sqrt(sigma)
    return v, sigma

def svdPowerIter(A):
    B = np.copy(A)
    n = B.shape[1]
    for j in range(1, n+1):
        T = np.matmul(B.transpose(), B)
        v, sigma = powerIter(T)
        u =  np.dot(B, v) / sigma
        B = B -  sigma * np.outer(u, v)
        print("j {} v {} sigma {} u {}".format(j, v, sigma, u))

    print(np.matmul(U.transpose(), U))

def svdPowerIter2(A):
    n = A.shape[1]
    B = np.copy(A)
    P = np.matmul(A.transpose(), A)
    vList = [None] * n
    sigmaList = [None] * n
    uList = [None] * n
    for j in range(0, n):
        #T = P 
        lSum = np.zeros((n, n))
        for i in range(0, j):
            lSum += np.outer(vList[i], vList[i])
        print(lSum)
        lSum = np.eye(n) - lSum
        T = lSum @ P @ lSum 
        print("T {}".format(T))
        vList[j], sigmaList[j] = powerIter(T)
        uList[j] =  np.dot(A, vList[j]) / sigmaList[j]
        print("j {} v {} sigma {} u {}".format(j, vList[j], sigmaList[j], uList[j]))

#T = np.matmul(A.transpose(), A)
#print(T)
#v, sigma = powerIter(T)
#u =  np.dot(A, v) / sigma
#print("v {} sigma {} u {}".format(v, sigma, u))

U, Sigma, V = np.linalg.svd(A)
print("U {}".format(U))
print("V {}".format(V))
print("Sigma{}".format(Sigma))

svdPowerIter(A)
#svdPowerIter2(A)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]]
U [[-0.17330388  0.72332071  0.26166214  0.61506572]
 [ 0.6804161   0.15967861  0.65954611 -0.27665068]
 [-0.3691172   0.56196726 -0.06456915 -0.73741177]
 [ 0.60889423  0.36810689 -0.7016856   0.0371813 ]]
V [[-0.46899222  0.48421055 -0.73863823]
 [ 0.81556069 -0.08355492 -0.57260749]
 [-0.33897945 -0.87095276 -0.35571649]]
Sigma[3.85390339 2.32027447 0.64996275]
j 1 v [ 0.46895999 -0.48420725  0.73866086] sigma 3.8539033867443577 u [ 0.17328667 -0.6804199   0.36910383 -0.60890299]
j 2 v [-0.81557922  0.08357405  0.57257831] sigma 2.3202744689687114 u [-0.72333208 -0.15963397 -0.56199148 -0.36806694]
j 3 v [0.33897945 0.87095276 0.35571649] sigma 0.6499627501147641 u [-0.26166214 -0.65954611  0.06456915  0.7016856 ]
[[ 0.03003423  0.49215906 -0.096584    0.37450997]
 [ 0.49215906  0.02549726  0.37064332 -0.10183702]
 [-0.096584   