In [11]:
""""
Figaro times collection times script. 
"""
import numpy as np
import pandas as pd
import os
import regex as re
from openpyxl import load_workbook, Workbook
from openpyxl.utils.cell import get_column_letter

path_src = "/local/scratch/Figaro/tests_path/figaro-code"
exp_names = ["svd_mkl_dc", "svd_figaro"]
exp_comp = {"svd_mkl_dc"}
exp_fig = "svd_figaro"
exp_paths = {"svd_mkl_dc": "/local/scratch/Figaro/tests_path/figaro-code/dumps/decomp_alg/svd/divide_and_conquer/sing_vals_100/col_major/s_only", "svd_figaro": "/local/scratch/Figaro/tests_path/figaro-code/dumps/figaro/svd/divide_and_conquer/sing_vals_100/s_onlyt/hread48"}
#db_names = ["DBRetailer", "DBFavorita", "DBYelp"]
db_names = ["DBRetailer", "DBFavorita", "DBYelp"]
join_orders = {"DBRetailer": "LocationRoot", "DBFavorita": "StoresRoot", "DBYelp": "BusinessRoot"}
start_per = 10
end_per = 100
per_inc = 10

csv_name = "R.csv"
numeric_const_pattern = r"Relative error is: ([+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?)"
rx = re.compile(numeric_const_pattern)

df_measurement_exps = {}

df_measurement = pd.DataFrame(columns=db_names)

for db_name in db_names:
    join_order = join_orders[db_name]

    db_name_per = "{}{}".format(db_name, "100")
    

    exp_path = exp_paths["svd_figaro"]
    path_csv = os.path.join(exp_path, db_name_per,
    join_order, csv_name)
    np_figaro = pd.read_csv(path_csv, header=None).astype(float).to_numpy()
    
    exp_path = exp_paths["svd_mkl_dc"]
    path_csv = os.path.join(exp_path, db_name_per,
    join_order, csv_name)
    np_mkl = pd.read_csv(path_csv, header=None).astype(float).to_numpy()
    
    for db_idx, percent in enumerate(range(start_per, end_per + 1, per_inc)):
        per_val = (int)(percent / 100.0 * np_figaro.shape[0])
        per_prev_val = (int)((percent - 10) / 100.0 * np_figaro.shape[0]) + 1
        print("percent", per_val)
        np_fig_per = np_figaro[per_prev_val:per_val]
        np_mkl_per = np_mkl[per_prev_val:per_val]
        np_diff = np_fig_per - np_mkl_per
        print(np_diff)

        abs_err = np.linalg.norm(np_diff, ord='fro')
        abs_err_comp  = np.linalg.norm(np_mkl_per, ord='fro')
        #if (percent == 100):
            #print(np_mkl_per)
            #print(np_figaro)
        relative_frob_norm = abs_err / abs_err_comp

        df_measurement.at[percent, db_name] = relative_frob_norm
df_measurement.to_csv("sing_values.csv", sep="\t")







percent 4
[[5.06639481e-07]
 [6.85453415e-07]
 [0.00000000e+00]]
percent 8
[[4.17232513e-07]
 [2.98023224e-08]
 [5.96046448e-08]]
percent 12
[[ 1.21071935e-08]
 [-6.23986125e-08]
 [-9.17352736e-08]]
percent 17
[[1.69966370e-08]
 [1.51339918e-08]
 [6.71879388e-06]
 [2.18395144e-07]]
percent 21
[[6.72691385e-07]
 [1.45810191e-08]
 [4.39467840e-09]]
percent 25
[[1.73691660e-07]
 [2.97950464e-08]
 [1.22490746e-07]]
percent 30
[[ 3.54702934e-09]
 [-2.35741027e-09]
 [ 2.37014319e-09]
 [ 4.30336513e-08]]
percent 34
[[2.05573087e-08]
 [1.85746103e-08]
 [1.46706043e-08]]
percent 38
[[5.30117177e-08]
 [1.85118552e-08]
 [2.76299943e-08]]
percent 43
[[1.36939207e-08]
 [9.80674031e-09]
 [2.11181828e-09]
 [1.92450500e-09]]
percent 3
[[2.84500420e-05]
 [3.61003913e-07]]
percent 6
[[ 9.06766218e-10]
 [-1.21872290e-10]]
percent 9
[[2.21007213e-10]
 [6.42558007e-10]]
percent 12
[[1.19871402e-09]
 [1.85536919e-10]]
percent 15
[[ 1.50066626e-11]
 [-1.97815098e-11]]
percent 18
[[ 3.68345354e-11]
 [-6.13908

In [6]:
import matplotlib.pyplot as plt

plt.figure("name", figsize=(16, 8), dpi=80)
plt.xlabel("Percentage of the join size")
plt.ylabel("Relative error")

plt.title("Relative error in the computation of singular values using SVD-Figaro in comparison to SVD-MKL")

plt.yscale('log', base=10)
plt.locator_params(axis='x', nbins=6)
plt.locator_params(axis='x', nbins=10)
db_markers =  {"DBFavorita": "^", "DBYelp": "s", "DBRetailer": "x"}
db_colors = {"DBRetailer": "r", "DBFavorita": "g", "DBYelp": "y"}
comp_path = 
for exp_name in exp_names:
    df_measurement = df_measurement_exps[exp_name]
    for db_name in df_measurement:
        db_color = db_colors[db_name]
        db_marker = db_markers[db_name]
        plt.plot(df_measurement[db_name], "-" + db_color + db_marker, label="{} {}".format(exp_name, db_name))
plt.legend(loc="upper left")
plt.savefig('sing_val_accur.pdf')   # save the figure to file

plt.show()

SyntaxError: invalid syntax (3509863822.py, line 14)